### ISSUE TITLE
Connector warnings in log

### ISSUE THREAD

**Issue by mikrobestie** [alump/LazyLayouts#4] opened 2015-03-12 14:53 UTC
Hello,

i tried your addon and in most cases, it works good! But after some time, I receive warnings in log like:

`2015-03-12 15:35:09.914[WARN ][xec-6][in.server.communication.ServerRpcHandler  382]-RPC call to org.vaadin.alump.lazylayouts.client.LazyLayoutServerRpc.onLazyLoadRequest received for connector 1626 but no such connector could be found. Resynchronizing client.`

also:

`2015-03-12 15:41:44.909[WARN ][xec-4][in.server.communication.ServerRpcHandler  269]-Ignoring RPC call for disabled connector org.vaadin.alump.lazylayouts.LazyVerticalLayout`

I'm using latest version (0.1.1). Is it  abug or am I doing something wrong? 
Thanks!

**Comment by alump** [comment] 2015-03-12 15:20
What Vaadin version you use? What is your component hierarchy (above LazyLayouts, it's parent, grand parent...)? Do you set LazyLayout (or it's parents) visibility to false? Have you removed it from it's parent to another component?

**Comment by mikrobestie** [comment] 2015-03-12 15:59
I use LazyVerticalLayout inside TabSheet. I tried it now and it happens when I switch tabs. The full hierarchy is kinda difficult:

-UIConnector (44)
-HorizontalLayoutConnector (46)
+CssLayoutConnector (47)
-HorizontalLayoutConnector (67)
-TabsheetConnector (480)
-VerticalLayoutConnector (481)
-PanelConnector (482)
+LazyVerticalLayoutConnector (483)

I use Vaadin version 7.4.1

**Comment by alump** [comment] 2015-03-15 22:22
I assume issue could be caused by TabsSheet. I have to write some tests. (When switching between tabs of TabSheet, strange things can happen).

**Comment by alump** [comment] 2015-03-17 20:38
Yes, LazyVerticalLayout misbehaves inside TabSheet, fixing...

**Comment by alump** [comment] 2015-03-17 21:51
Warning were nothing fatal, but fixed in 0.1.3

**Closed by alump** 2015-03-17 21:51 UTC
