### ISSUE TITLE
onLazyComponentRequest not being called?

### ISSUE THREAD

**Issue by stozk** [alump/LazyLayouts#6] opened 2015-11-02 09:25 UTC
Hi,

I've tried to put this into a Spring Boot Vaadin application.

The layout initialization works, then the updateIndicatorText() method gets called but after that nothing will happen. I'll only get loading indicator at the bottom, but the onLazyComponentRequest () doesn't get called.

Do you know what might be the problem?

Thanks & BR

**Comment by alump** [comment] 2015-11-02 09:57
Is lazylayout as content of panel or window?

**Comment by stozk** [comment] 2015-11-02 10:09
Lazylayout it inside another Verticallayout (overviewlayout) which is inside a tabsheet.

Is this a problem?

**Comment by alump** [comment] 2015-11-02 11:12
Parent needs to be scrollable. VerticalLayout isn't, so it will not get scrolling events. So lazylayout should be direct child of tabsheet. Anyhow, it might be that tabsheet support has also some issues, as I think I have only tested component with window and panel.

**Comment by stozk** [comment] 2015-11-02 11:16
Ah well ok I'm gonna fiddle around a bit and try to fix it thanks.

**Comment by alump** [comment] 2015-11-02 11:21
Please inform if it doesn't work as direct child of tabsheet. As then there is something to fix.

**Comment by stozk** [comment] 2015-11-02 11:27
I have replaced the overviewlayout VerticalLayout with the LazyVerticalLayout, so its parent now should be the tabsheet, but it still won't work :/

**Comment by alump** [comment] 2015-11-02 11:41
Actually 0.1.3 should work fine inside TabSheet. So...

Is the height of tabsheet defined and height of lazylayout undefined?

Do you see the scrollbar in your tabsheet (when lazylayout is visible)?

Can you email screenshot of your view to me? sami.viitanen@vaadin.com

**Comment by stozk** [comment] 2015-11-02 11:50
Yes, the tabsheet is set to .setSizeFull(), the lazylayout has an undefined size.
I can see the scrollbar: https://www.dropbox.com/s/mavczxvkxd1jb9q/lazylayout.PNG?dl=0

**Comment by alump** [comment] 2015-11-02 12:37
Ok, and even if you scroll up and down that tabsheet content, it doesn't help?

**Comment by stozk** [comment] 2015-11-02 13:05
No, it just wont fire the event. I'm not sure if it's because it's inside a more complex ui layout maybe?

**Comment by alump** [comment] 2015-11-02 13:23
Maybe, if you run you app with ?debug, do you get any client side errors or warnings?

**Comment by stozk** [comment] 2015-11-02 15:51
I think that the problem might be that the widget just isn't properly integrated into my project, but I'm not sure where I could have made error since the demo project is configured differently.

I tried to set up a simple Spring Boot Project with vaadin and put in the Tab demo from the demo project. It results in the same problem, so I guess the client part of the widget isn't properly loading because it's not firing the event when scrolling.

If would be nice if you could have a look at it if you have the time:

https://www.dropbox.com/s/ligzvmk87rssqlx/lazyload.zip?dl=0

I guess I'm missing some annotation or configuration file, but I'm not sure what to look for.

**Comment by alump** [comment] 2015-11-02 16:05
Unless I missed something, your application does not compile custom widgetset. As my add-on extends client side, you need to build custom widgetset to have those parts included. If vaadin's default widgetset is used, then LazyVerticalLayout will behave as VerticalLayout (as it extends VerticalLayout, but will not explode if client side is missing the extension part).

Please check the demo project of LazyLayout:
https://github.com/alump/LazyLayouts/tree/master/lazylayouts-demo

Steps:
- define custom widgetset file in style of: https://github.com/alump/LazyLayouts/blob/master/lazylayouts-demo/src/main/resources/org/vaadin/alump/lazylayouts/demo/DemoWidgetSet.gwt.xml

- annotate servlet with widgetset name, or define widgetset in web.xml file. Example of annotated servlet class (inside UI class):
https://github.com/alump/LazyLayouts/blob/master/lazylayouts-demo/src/main/java/org/vaadin/alump/lazylayouts/demo/DemoUI.java

- make sure your pom.xml has vaadin plugin with compile-widgetset step, example of pom.xml (rows 199-235):
https://github.com/alump/LazyLayouts/blob/master/lazylayouts-demo/pom.xml

**Comment by stozk** [comment] 2015-11-02 16:10
Thank you very much, I just solved the problem. It was partly a layer 8 problem, because I was compiling the widgets, but I didn't put the declaration in the proper widgetset file...

It works now, thank you very much for your time and help again ;-)

**Comment by alump** [comment] 2015-11-02 16:11
Good, closing the issue.

**Closed by alump** 2015-11-02 16:11 UTC

**Comment by gregmazur** [comment] 2016-03-30 15:49
Well, I don`t wanna look as a person who didn`t put any effort to understand the problem, but I just ran into the same problem. I m using Spring Boot as well, added all the details as you mentioned before(however Push annotation gives me an exception and http response 500... I did found a solution though 
 [here](https://github.com/Artur-/portal-push)
 but didn`t get the list moving) and I keep having the the circle moving but nothing else...
Also my Idea cannot resolve com.vaadin.DefaultWidgetSet at [CustomWidget.gwt.xml](https://github.com/gregmazur/PeopleFinder/blob/master/src/main/resources/people.network.UI/CustomWidget.gwt.xml)
So seriously @stozk how you managed this?
@alump if you could look [the project](https://github.com/gregmazur/PeopleFinder) I appreciate it much .
Thank you

**Comment by stozk** [comment] 2016-03-30 17:46
Dunno, I just put     <inherits name="org.vaadin.alump.lazylayouts.LazyLayoutsWidgetSet" />   in my CustomWidget.gwt.xml and it works.

**Comment by alump** [comment] 2016-03-30 18:44
> Idea cannot resolve com.vaadin.DefaultWidgetSet

Maybe your project does not have vaadin-client as dependency? Maybe it has vaadin-client-compiled that isn't suitable, if you want to compile your own version.

**Comment by gregmazur** [comment] 2016-03-30 21:48
I thought if I add `vaadin-bom` it imports all of the dependencies in it. but apparently it is not. 
Well, now when I added client-compiler dependency, I am getting 
`Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/jsp/JspFactory
	at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:77)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.handleDeferredInitialize(JettyEmbeddedServletContainer.java:163)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:110)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:117)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:689)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:958)
	at de.test.vaadin.demo.LazyloadApplication.main(LazyloadApplication.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: javax.servlet.jsp.JspFactory`
I got rid of it by adding
`<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-jetty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-jasper</artifactId>
        </dependency>`
and yet the circle only moving ....
and all this stuff I ve done to uploaded by @stozk project...
Guess I`m doing something wrong...

**Comment by stozk** [comment] 2016-03-31 06:13
Do you have this under build/plugins in your pom.xml
```
<plugin>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-maven-plugin</artifactId>
				<version>${vaadin.plugin.version}</version>

				<configuration>
					<extraJvmArgs>-Xmx512M -Xss1024k</extraJvmArgs>
					<!-- We are doing "inplace" but into subdir VAADIN/widgetsets. This 
						way compatible with Vaadin eclipse plugin. -->
					<webappDirectory>${basedir}/src/main/webapp/VAADIN/widgetsets
					</webappDirectory>
					<hostedWebapp>${basedir}/src/main/webapp/VAADIN/widgetsets
					</hostedWebapp>
					<!-- Most Vaadin apps don't need this stuff, guide that to target -->
					<persistentunitcachedir>${project.build.directory}</persistentunitcachedir>
					<deploy>${project.build.directory}/gwt-deploy</deploy>
					<!-- Compile report is not typically needed either, saves hundreds of 
						mb disk -->
					<compileReport>false</compileReport>
					<noServer>true</noServer>
					<!-- Remove draftCompile when project is ready -->
					<draftCompile>false</draftCompile>

					<style>OBF</style>
					<strict>true</strict>
					<runTarget>http://localhost:8080/</runTarget>
				</configuration>
				
				<executions>
					<execution>
						<goals>
							<goal>clean</goal>
							<goal>resources</goal>
							<goal>update-theme</goal>
							<goal>update-widgetset</goal>
							<goal>compile-theme</goal>
							<goal>compile</goal>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

and this under pluginManagement/plugins:

 ```
<plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>com.vaadin</groupId>
                                        <artifactId>
                                            vaadin-maven-plugin
                                        </artifactId>
                                        <versionRange>
                                            [7.2.4,)
                                        </versionRange>
                                        <goals>
                                            <goal>clean</goal>
											<goal>resources</goal>
											<goal>update-theme</goal>
											<goal>update-widgetset</goal>
											<goal>compile-theme</goal>
											<goal>compile</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
```

**Comment by gregmazur** [comment] 2016-04-01 13:52
yep, I m a little confused now about which plugin I should launch. Did you use spring boot included Tomcat server? Cause if I use vaadin plugin it says there is no server... However if I just launch it thru main, the circle keeps moving but nothing else

**Comment by stozk** [comment] 2016-04-01 19:52
Yes, I just use spring boot with the embedded tomcat. You can try to generate a project template for spring boot starter + vaadin with https://start.spring.io/ , maybe you have just a missing dependency or some error in yours.

**Comment by gregmazur** [comment] 2016-04-05 14:27
don`t know, I`m using your project https://github.com/gregmazur/lazyload
